inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rake.yml
    - lib/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 3.0.0
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - smart_container.gemspec
    - bin/console
