---
language: ruby
cache: bundler
before_install:
- gem install bundler -v 2.1.2
script:
- bundle exec rake rubocop
- bundle exec rake rspec
jobs:
  fast_finish: true
  include:
  - rvm: 2.4.9
    os: [linux, osx]
  - rvm: 2.5.7
    os: [linux, osx]
  - rvm: 2.6.5
    os: [linux, osx]
  - rvm: 2.7.0
    os: [linux, osx]
  - rvm: ruby-head
    os: [linux, osx]
  - rvm: jruby-head
    os: [linux, osx]
  allow_failures:
  - rvm: ruby-head
    os: [linux, osx]
  - rvm: jruby-head
    os: [linux, osx]
